namespace RegalEdu.Domain.Enumerations
{
    public enum LocalizationKey
    {
        ActionFailed,
        Delete,
        Division,
        EmailAlreadyExists,
        EmployeeATIDAlreadyExists,
        EntityNotFound,
        ERR_SAVE_NO_EFFECT,
        ERR_TOO_MANY_RETRY,
        ERR_UNKNOWN,
        ModelCodeAlreadyExists,
        ModelNameAlreadyExists,
        ModelNotFound,
        MSG_CREATE_SUCCESS,
        MSG_DELETE_SUCCESS,
        MSG_UPDATE_SUCCESS,
        NoModelToAction,
        OnlyOneDefaultGroup,
        PasswordCannotBeEmpty,
        PasswordResetEmailSubject,
        PasswordResetError,
        PasswordResetError_ContactSupport,
        PasswordResetError_TryAgain,
        PasswordResetErrorTitle,
        PasswordResetFailed,
        PasswordResetLinkEmailSubject,
        PasswordResetSuccess,
        PasswordResetSuccess_CloseWindow,
        PasswordResetSuccess_EmailNotice,
        PasswordResetSuccessTitle,
        UnableToCastDbSet,
        UnexpectedError,
        UpdateAccountGroupFailed,
        User,
        UserNameAlreadyExists,
        UserNotFound,
        NoModelToDelete,
        EntityWithIdNotFound,
        PrefixTableColumnRequired,
        InvalidDbContextInstance,
        NoModelToRestore,
        MSG_RESTORE_SUCCESS,
        EntityNotDeleted,
        MSG_RESTORE_RESULT,
        EntityDeleteFailed,
        AdmissionsQuotaMustBeDraftToDelete,
        MSG_DELETE_RESULT,
        MustHasAtLeastOneDepartment,

        InvalidCategoryType,
        AgeGrIdNotFound,

        ActionException,
        CreateNewEmployee,
        ERR_SEND_EMAIL,
        MustHasAtLeastOneCompany,
        ERR_FILE_UPLOAD_FAILED,
        InvalidOrderRange,
        LearningRoadMapIdNotFound,
        //Hải
        InvalidEventCategory,
        ERR_CREATE_FAILED,
        InvalidGuidFormat,
        ERR_DUPLICATE_VALUE,
        ERR_CONCURRENCY,

        ERR_UPDATE_FAILED,

        InvalidIdFormat,
        CreateNewTeacher,
        MSG_APPROVE_CREATE_SUCCESS,
        APPROVED,
        REJECTED,
        ERR_DATA_INCONSISTENCY,
        GeneralDeleteError,
        ERR_INVALID_VALUE,
        MSG_UPDATE_SUCCESS_NOCHANGE,
        CreateNewStudent

    }

}

